name: ShapeBlock Installer CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Run security scan
      uses: securego/gosec@master
      with:
        args: ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: make build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: shapeblock-installer
        path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: shapeblock-installer
        path: bin/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/shapeblock-installer
          bin/shapeblock-installer-linux-amd64
